# ----- FIX VIM COLOR SCHEME IN TMUX -----
# enable undercurl and RGB color support
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Alacritty specific settings
if-shell '[ "$TERM" = "alacritty" ]' {
    set -g default-terminal "alacritty"
    set -ag terminal-overrides ",alacritty:RGB"
}
if-shell '[ "$TERM" = "xterm-kitty" ]' {
    set -g default-terminal "xterm-kitty"
}
if-shell '[ "$TERM" = "wezterm" ]' {
    set -g default-terminal "wezterm"
}

set -g history-limit 10000


# ----- PREVENT DELAY FOR VIM `CTRL + [` -----
set -sg escape-time 0


# ----- SET NEW WINDOW INITIAL PATH BASED FROM CURRENT WINDOW -----
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


bind-key i run-shell "tmux neww ~/utils/cht.sh/main"
bind-key "C-p" run-shell "tmux neww ~/utils/tmux/tmux-sessionizer"
bind-key "C-l" run-shell "~/utils/tmux/tmux-clear-windows"
# ----- BIND FOR MOVING-WINDOW
bind-key k swap-window -t -1\; select-window -t -1
bind-key j swap-window -t +1\; select-window -t +1


# ----- BEHAVIOUR CONFIGURATION -----
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"
set-option -g mouse on
set -s set-clipboard external
set -g focus-events on


# ----- Vi MODE -----
setw -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane # don't reset scroll upon mouse drag
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi "C-c" send-keys -X copy-selection
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi w send-keys -X next-word-end
bind-key -T copy-mode-vi / command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi "C-o" send-keys -X copy-pipe-and-cancel "xargs -I{} ~/utils/tmux/tmux-smart-edit {}"


# ----- THE BAR BELOW CONFIGURATION ----
set-option -g status-style bg=default
set-option -g status-style fg=colour249
set-option -g status-left-length 100
# set-option -g status-right-length 100
set-option -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=50:pane_title}\" %H:%M"
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F'
setw -g window-status-format ' #I#[fg=colour247]:#[fg=colour247]#W#[fg=colour247]#F'
