function tinted-firefox --description 'Generate Firefox userChrome.css from the active tinted-shell theme'
    set -l theme ~/.config/tinted-theming/base16_shell_theme
    if not test -e $theme
        echo "no active tinted theme"
        return 1
    end

    # default profile is machine-specific — resolve it from profiles.ini
    set -l ffdir ~/Library/Application\ Support/Firefox
    set -l rel (awk -F= '/^\[Install/{f=1} f && /^Default=/{print $2; exit}' $ffdir/profiles.ini 2>/dev/null)
    if test -z "$rel"
        echo "Firefox profile not found (has Firefox ever been run?)"
        return 1
    end
    set -l profile $ffdir/$rel
    mkdir -p $profile/chrome

    # colorNN="rr/gg/bb" -> hex; base16 themes alias brights (color09="$color01")
    # slot -> role: 0=bg 18=bg-alt(base01) 19=selection(base02) 8=dim(base03)
    #               20=muted(base04) 7=fg(base05) 4=accent(base0D)
    set -l hex (awk -F'"' '
        /^color[0-9]+="[0-9a-fA-F]{2}\// { n=substr($1,6,2)+0; gsub("/","",$2); c[n]=$2 }
        /^color[0-9]+="\$color[0-9]+"/   { n=substr($1,6,2)+0; ref[n]=substr($2,7)+0 }
        END { for (n in ref) c[n]=c[ref[n]]
              split("0 18 19 8 20 7 4", want, " ")
              for (i=1; i<=7; i++) print c[want[i]] }' $theme)
    set -l bg "#$hex[1]"
    set -l bgalt "#$hex[2]"
    set -l sel "#$hex[3]"
    set -l dim "#$hex[4]"
    set -l muted "#$hex[5]"
    set -l fg "#$hex[6]"

    printf '%s\n' "\
/* generated by tinted-firefox from $(basename (readlink $theme)) — do not edit */
#navigator-toolbox, #TabsToolbar, #nav-bar, #PersonalToolbar {
    background-color: $bg !important;
    color: $fg !important;
}
#navigator-toolbox { border-bottom: 1px solid $bgalt !important; }
.tab-background { background: transparent !important; border: none !important; box-shadow: none !important; }
.tabbrowser-tab[selected] .tab-background { background: $sel !important; }
.tabbrowser-tab .tab-label { color: $muted !important; }
.tabbrowser-tab[selected] .tab-label { color: $fg !important; }
#urlbar-background, #searchbar { background-color: $bgalt !important; }
#urlbar { color: $fg !important; }
toolbar .toolbarbutton-1 { fill: $muted !important; color: $muted !important; }" \
        >$profile/chrome/userChrome.css

    # userChrome.css is ignored unless this pref is on (read at startup)
    set -l pref 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
    grep -qs 'legacyUserProfileCustomizations.stylesheets", true' $profile/user.js
    or echo $pref >>$profile/user.js

    echo "userChrome.css written for $(basename (readlink $theme)) — restart Firefox to apply"
end
