#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents ~/Documents/personal ~/.local/share/nvim/lazy ~/.config ~/Downloads ~ ~/utils/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
existingSession=$(tmux list-sessions -F '#S' | grep "^$selected_name$")

if [[ -z $TMUX ]]; then
    # not in tmux session
    if [[ -z $existingSession ]]; then
        if [[ -f $selected/.vim/tmux-session ]]; then
            $selected/.vim/tmux-session restore
            tmux attach-session -t $selected_name
        else
            tmux new-session -s $selected_name -c $selected
        fi
    else
        tmux attach -t $selected_name
    fi
else
    # inside tmux session
    current_session=$(tmux display-message -p '#S')

    if [[ -z $existingSession ]]; then
        if [[ -f $selected/.vim/tmux-session ]]; then
            $selected/.vim/tmux-session restore
        else
            tmux new-session -ds $selected_name -c $selected
        fi
    fi
    tmux switch-client -t $selected_name

    # If we came from a throwaway bootstrap session (default numeric name like
    # "0" with a single pane), kill it so it doesn't linger after switching.
    if [[ $current_session =~ ^[0-9]+$ && $current_session != $selected_name ]]; then
        if [[ $(tmux list-panes -s -t "$current_session" 2>/dev/null | wc -l) -eq 1 ]]; then
            tmux kill-session -t "$current_session"
        fi
    fi
fi
