return {
	"folke/ts-comments.nvim",
	event = "CursorMoved",
	opts = {
		lang = {
			astro = "<!-- %s -->",
			c = "// %s",
			cpp = "// %s",
			css = "/* %s */",
			gleam = "// %s",
			glimmer = "{{! %s }}",
			graphql = "# %s",
			handlebars = "{{! %s }}",
			hcl = "# %s",
			html = "<!-- %s -->",
			ini = "; %s",
			php = "// %s",
			rego = "# %s",
			rescript = "// %s",
			sql = "-- %s",
			svelte = "<!-- %s -->",
			terraform = "# %s",
			tsx = {
				_ = "// %s",
				call_expression = "// %s",
				comment = "// %s",
				jsx_attribute = "// %s",
				jsx_element = "{/* %s */}",
				jsx_fragment = "{/* %s */}",
				spread_element = "// %s",
				statement_block = "// %s",
			},
			javascript = {
				_ = "// %s",
				call_expression = "// %s",
				comment = "// %s",
				jsx_attribute = "// %s",
				jsx_element = "{/* %s */}",
				jsx_fragment = "{/* %s */}",
				spread_element = "// %s",
				statement_block = "// %s",
			},
			twig = "{# %s #}",
			typescript = "// %s",
			vim = '" %s',
			vue = "<!-- %s -->",
		},
	},
}
