#!/usr/bin/env bash

selected=$(cat ~/utils/cht.sh/languages ~/utils/cht.sh/commands | fzf)
[[ -z $selected ]] && exit 0

read -p "Enter Query: " query

if grep -qs "$selected" ~/utils/cht.sh/languages; then
    query=$(echo "$query" | tr ' ' '+')
    curl "cht.sh/$selected/$query" | less -R
else
    curl -s "cht.sh/$selected~$query" | less -R
fi

