#!/usr/bin/env bash
selected=`cat ~/utils/cht.sh/languages ~/utils/cht.sh/commands | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" ./languages; then
    query=`echo $query | tr ' ' '+'`
    echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done
else
    curl -s cht.sh/$selected~$query | less
fi
