local M = {}

local color_utils = require("mirec/mirec_color_utils")

local colorscheme = {
	{ "Boolean", { ctermfg = 252 } },
	{ "Character", { ctermfg = 252 } },
	{ "ColorColumn", { ctermbg = 233 } },
	{ "Comment", { ctermfg = 8 } },
	{ "Conceal", { ctermfg = 8 } },
	{ "Conditional", { ctermfg = 252 } },
	{ "Constant", { ctermfg = 252 } },
	{ "Cursor", { ctermfg = 9, ctermbg = 24, cterm = { bold = false, nocombine = true } } },
	{ "CursorColumn", { ctermbg = 232 } },
	{ "CursorLine", { ctermbg = 233 } },
	{ "CursorLineNr", { ctermfg = 255, ctermbg = 125, cterm = { bold = false, nocombine = true } } },
	{ "CursorLineSign", { ctermfg = 255, ctermbg = 125, cterm = { bold = false, nocombine = true } } },
	{ "Debug", { ctermfg = 181, cterm = { bold = false } } },
	{ "Define", { ctermfg = 252, cterm = { bold = false } } },
	{ "Delimiter", { ctermfg = 252 } },
	{ "DiffAdd", { ctermbg = 22 } },
	{ "DiffChange", { ctermbg = 24 } },
	{ "DiffDelete", { ctermfg = 234, ctermbg = 88 } },
	{ "DiffText", { ctermfg = 231, ctermbg = 31, cterm = { bold = false } } },
	{ "Directory", { ctermfg = 231, cterm = { bold = false } } },
	{ "Error", { ctermfg = 231, ctermbg = 9 } },
	{ "ErrorMsg", { ctermfg = 16, ctermbg = 6 } },
	{ "Exception", { ctermfg = 252 } },
	{ "Float", { ctermfg = 252 } },
	{ "FoldColumn", { ctermfg = 181, ctermbg = 235 } },
	{ "Folded", { ctermfg = 181, ctermbg = 16 } },
	{ "Function", { ctermfg = 252 } },
	{ "Identifier", { ctermfg = 252 } },
	{ "Include", { ctermfg = 252 } },
	{ "Keyword", { ctermfg = 252 } },
	{ "Label", { ctermfg = 252 } },
	{ "LineNr", { ctermfg = 244, ctermbg = 234 } },
	{ "Macro", { ctermfg = 252 } },
	{ "MatchParen", { ctermfg = 255, ctermbg = 125, cterm = { bold = true, nocombine = true } } },
	{ "NonText", { ctermfg = 8 } },
	{ "Normal", { ctermfg = 252 } },
	{ "Number", { ctermfg = 252 } },
	{ "Operator", { ctermfg = 252 } },
	{ "Special", { ctermfg = 252 } },
	{ "SpecialChar", { ctermfg = 181, cterm = { bold = false } } },
	{ "SpecialComment", { ctermfg = 181, cterm = { bold = false } } },
	{ "SpecialKey", { ctermfg = 8 } },
	{ "SpellBad", { ctermfg = 174, ctermbg = 233, undercurl = true, cterm = { underline = true } } },
	{ "Statement", { ctermfg = 252 } },

	{ "Pmenu", { ctermfg = 252, ctermbg = 235 } },
	{ "PmenuSel", { ctermfg = 16, ctermbg = 156 } },
	{ "PmenuSbar", { ctermfg = 248, ctermbg = 237 } },
	{ "PmenuThumb", { ctermfg = 248, ctermbg = 156 } },
	{ "PreCondit", { ctermfg = 252, cterm = { bold = false } } },
	{ "PreProc", { ctermfg = 252 } },
	{ "Question", { ctermfg = 231, cterm = { bold = false } } },
	{ "Repeat", { ctermfg = 252, cterm = { bold = false } } },
	{ "Search", { ctermfg = 227, ctermbg = 16, cterm = { bold = false, reverse = true } } },
	{ "IncSearch", { ctermfg = 16, ctermbg = 131 } },
	{ "SignColumn", { ctermfg = 244, ctermbg = 233 } },
	{ "doxygenBrief", { ctermfg = 249, cterm = { bold = false } } },
	{ "doxygenSpecialOnelineDesc", { ctermfg = 123 } },
	{ "StatusLine", { ctermbg = 16, ctermfg = 28, cterm = { bold = false } } },
	{ "StatusLineNC", { ctermfg = 234, ctermbg = 252 } },
	{ "StorageClass", { ctermfg = 252 } },
	{ "String", { ctermfg = 252 } },
	{ "Structure", { ctermfg = 252 } },
	{ "Tag", { ctermfg = 252 } },
	{ "Title", { ctermfg = 252 } },
	{ "Todo", { ctermfg = 231, cterm = { bold = true } } },
	{ "Typedef", { ctermfg = 252 } },
	{ "Type", { ctermfg = 252 } },
	{ "Underlined", { ctermfg = 81, cterm = { underline = true } } },
	{ "VertSplit", { ctermfg = 236, ctermbg = 16 } },
	{ "Visual", { ctermfg = 210, ctermbg = 236 } },
	{ "VisualNOS", { ctermfg = 234, ctermbg = 210, cterm = { bold = false, underline = true } } },
	{ "WarningMsg", { ctermfg = 231, ctermbg = 234, cterm = { bold = false } } },
	{ "WildMenu", { ctermfg = 16, ctermbg = 181 } },
	{ "Whitespace", { ctermfg = 242 } },
	{ "ModeMsg", { ctermfg = 181, cterm = { bold = false } } },
	{ "MoreMsg", { ctermfg = 231, cterm = { bold = false } } },

	{ "OverLength", { ctermbg = 237 } },
	{ "WarnLength", { ctermbg = 235 } },

	{ "BufferSelected", { ctermfg = 227, ctermbg = 16, cterm = { bold = false, reverse = true } } },
	{ "BufferNormal", { ctermfg = 252, ctermbg = 16 } },
	{ "diffFile", { link = "Conceal" } },

	{ "LspSignatureActiveParameter", { cterm = { bold = true, italic = true } } },

	{ "CmpItemMenu", { ctermfg = 120, cterm = { italic = true } } },

	{ "CmpItemAbbrMatch", { cterm = { bold = true }, ctermfg = 231 } },
	{ "CmpItemAbbrMatchFuzzy", { cterm = { bold = true }, ctermfg = 231 } },
	{ "CmpItemAbbrMatchDefault", { cterm = { bold = true }, ctermfg = 231 } },
	{ "CmpItemAbbrMatchFuzzyDefault", { cterm = { bold = true }, ctermfg = 231 } },
	{ "CmpItemMenu", { cterm = { italic = true } } },
	{ "CmpItemAbbrDeprecated", { ctermfg = 244 } },

	{ "CmpItemKindField", { ctermfg = 255, ctermbg = 131 } },
	{ "CmpItemKindProperty", { ctermfg = 255, ctermbg = 131 } },
	{ "CmpItemKindEvent", { ctermfg = 255, ctermbg = 131 } },

	{ "CmpItemKindEnum", { ctermfg = 255, ctermbg = 28 } },
	{ "CmpItemKindKeyword", { ctermfg = 255, ctermbg = 28 } },

	{ "CmpItemKindConstant", { ctermfg = 255, ctermbg = 23 } },
	{ "CmpItemKindConstructor", { ctermfg = 255, ctermbg = 23 } },
	{ "CmpItemKindReference", { ctermfg = 255, ctermbg = 23 } },

	{ "CmpItemKindFunction", { ctermfg = 255, ctermbg = 90 } },

	{ "CmpItemKindStruct", { ctermfg = 255, ctermbg = 125 } },
	{ "CmpItemKindClass", { ctermfg = 255, ctermbg = 125 } },
	{ "CmpItemKindModule", { ctermfg = 255, ctermbg = 125 } },
	{ "CmpItemKindOperator", { ctermfg = 255, ctermbg = 125 } },

	{ "CmpItemKindVariable", { ctermfg = 255, ctermbg = 55 } },
	{ "CmpItemKindFile", { ctermfg = 255, ctermbg = 55 } },
	{ "CmpItemKindFolder", { ctermfg = 255, ctermbg = 55 } },
	{ "CmpItemKindSnippet", { ctermfg = 255, ctermbg = 55 } },

	{ "CmpItemKindUnit", { ctermfg = 255, ctermbg = 58 } },
	{ "CmpItemKindText", { ctermfg = 255, ctermbg = 58 } },

	{ "CmpItemKindMethod", { ctermfg = 255, ctermbg = 61 } },
	{ "CmpItemKindValue", { ctermfg = 255, ctermbg = 61 } },
	{ "CmpItemKindEnumMember", { ctermfg = 255, ctermbg = 61 } },

	{ "CmpItemKindInterface", { ctermfg = 255, ctermbg = 66 } },
	{ "CmpItemKindColor", { ctermfg = 255, ctermbg = 66 } },
	{ "CmpItemKindTypeParameter", { ctermfg = 255, ctermbg = 66 } },
}

M.setup = function(config)
	color_utils.setup_colorscheme(colorscheme, "mirec", "dark")
end

return M
