#!/usr/bin/env fish
# Kill stray LSP / dev-server / package-manager processes.
set patterns biome Biome next vtsls eslint_d eslint prettierd node bun bunx tsserver next-server yarn turbo watchman deno opencode tsgo
pkill -9 "^("(string join '|' $patterns)")"
