#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents ~/Documents/fun++ ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    if [[ -f $selected/.vim/tmux-session ]]; then
        $selected/.vim/tmux-session restore
        tmux attach-session -t $selected_name
    else
        tmux new-session -s $selected_name -c $selected
    fi
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    if [[ -f $selected/.vim/tmux-session ]]; then
        $selected/.vim/tmux-session restore
    else
        tmux new-session -ds $selected_name -c $selected
    fi
fi

tmux switch-client -t $selected_name
