[general]
    live_config_reload = true

[colors]
    draw_bold_text_with_bright_colors = true

[window]
    option_as_alt = "Both"
    decorations = "none"
    # startup_mode = "Maximized"

[font]
    normal = { family = "IoskeleyMonoNL Nerd Font" }
    size = 15.4
    bold = { family = "IoskeleyMonoNL Nerd Font" }
    italic = { family = "IoskeleyMonoNL Nerd Font" }
    bold_italic = { family = "IoskeleyMonoNL Nerd Font" }

[keyboard]
    bindings = [
        { key = "Key6", mods = "Control", chars = "\u001e" },
        { key = "F10", action = "ToggleMaximized" },
        { key = "F", mods = "Command|Control", action = "ToggleMaximized" },
        { key = "Tab", mods = "Control", chars = "\u001b[9;5u" },
        { key = "Return", mods = "Shift", chars = "\u001b[13;2u" }, # shift enter
        { key = "Escape", mods = "Command", action = "ClearLogNotice" }, # dismiss error banner
        { key = "[", mods = "Command|Control", action = "ClearLogNotice" },
    ]

[selection]
    save_to_clipboard = true

[[hints.enabled]]
    regex = "(~|\\.\\.?)?/?[\\w.@-]+(/[\\w.@-]+)*\\.\\w+(:\\d+)?"
    command = "/Users/ard/utils/tmux/tmux-smart-edit"
    post_processing = true
    mouse = { enabled = true, mods = "Command|Shift" }
